name: Django CI
env:
  SECRET_KEY: 'django-insecure-anf%9@%ji0+d3ozn-)7w9@%@+uf8gbrl8^rm1ja5=!m@6-5r)9'
  DEBUG : True
on:
  push:


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
